[package]
name = "rsast"
version = "0.1.0"
authors = ["Edoardo Rosa <edoardo.rosa90@gmail.com>"]

[dependencies]
primal = "0.3.2"
num = "0.4.0"
rand = "0.8"
num_cpus = "1.16.0"
ansi_term = "0.12.1"
num-bigint = { version = "0.4", features = ["rand"] }
